config/routes.rb
Rails.application.routes.draw do



  get 'user/index'

  get 'user/dashboard'

  get 'service_center/index'

  get 'service_center/dashboard'

# devise routes
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_for :service_centers, path: 'service_centers', controllers: { sessions: "service_centers/sessions", registrations: "service_centers/registrations" }

#routes
  resources :appointments, only: [:create, :update, :destroy]
  resources :autos, only: [:new, :create]

  match '/requests/appointments/complete/:id' => 'requests#complete', as: 'complete_request', via: :put

# nested routes
  resources :requests do
    resources :quotes
    collection do
      get "sc_dashboard" # generate  get "/requests/sc_dashboard"
    end
  end
  # resources :services, only: [:index]

# custom routes
  get "new_service", to: 'requests#new_service', as: :new_service
  
  get '/requests/add_quote/:id', to: 'requests#add_quote', as: 'add_quote'

  get "welcome", to: "welcome#index", as: :welcome


# root
  root 'welcome#index'

end

app/models/request.rb
class Request < ApplicationRecord
  before_validation :format_service
  belongs_to :user
  belongs_to :auto
  has_many :quotes, dependent: :destroy
  has_many :appointments, through: :quotes

  validates :service, presence: true

  serialize :service

  validates_associated :quotes

  def self.no_appointments
    left_outer_joins(:appointments).where(appointments: {id: nil})
  end
  def self.no_completed_appointments
    left_outer_joins(:appointments).where(appointments: {completed: false})
  end
  def self.completed_appointments
    left_outer_joins(:appointments).where(appointments: {completed: true})
  end

  def format_service
    self.service = service.compact.reject(&:empty?)
  end

  def display_as_sentence
    self.compact.reject(&:empty?).to_sentence
  end

  def self.with_no_quotes_by(service_center)
  joins(:quotes).
    where.not(quotes: { service_center_id: service_center.id })
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new]
  before_action :authenticate_service_center!, only: [:sc_dashboard, :add_quote]
  before_action :set_request, only: [:show, :edit, :update, :destroy]

    def sc_dashboard
      @requests = Request.where.not( id: Request.joins(:quotes).where(quotes: { service_center_id: current_service_center.id }).select(:id) ).includes(:appointments).where(appointments: {id: nil})
      @service_center = current_service_center
      @service_center_quotes = Quote.where(service_center_id: current_service_center.id).includes(:appointment).where(appointments: {quote_id: nil})
    end

    def complete
      @request = Appointment.find(params[:id])
      @request.completed = true
      @request.save
      redirect_to sc_dashboard_requests_path
    end
    # GET /requests
    # requests/index.html.erb
    # displays all requests
    def index
      @request = current_user.requests.last
      @appointments = current_user.appointments
      @appointments_uncomplete = current_user.appointments.completed_false
      @appointment = Appointment.new
    end

    # GET /requests/1
    # requests/show.html.erb
    # this will show the request
    # will also contain the comment form to create a new comment and show comments
    def show
      @request = Request.find(params[:id])
      @appointment = Appointment.new
    end

    def add_quote
      @request = Request.find(params[:id])
      @service_center = current_service_center
    end

    def new_service
      respond_to do |format|
        format.html
        format.js
        end
    end

    # GET /requests/new
    # requests/new.html.erb
    # form to create a new request
    def new
      @request = Request.new
      @auto = current_user.autos.last
    end

    # GET /requests/1/edit
    # edit.html.erb
    # form for editing request
    def edit
      @request = Request.find(params[:id])
    end

    # POST /requests
    # requests/index.html.erb
    # after new request created in form on new.html.erb above,
    # redirects to index page where new request will appear
    def create
      @request = Request.new(request_params)
      @request.user = current_user
      @request.auto = current_user.autos.last
      if @request.save
        flash[:notice] = 'Request was successfully created.'
        redirect_to requests_path
      else
        render :new
      end
    end

    # PATCH/PUT /requests/1
    # requests/show.html.erb
    # updates specific request
    def update
      respond_to do |format|
        if @request.update(request_params)
          format.html { redirect_to @request, notice: 'Request was successfully updated.' }
          format.json { render :show, status: :ok, location: @request }
        else
          format.html { render :edit }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        end
      end
    end
    # DELETE /requests/1
      # requests/show.html.erb
      # deletes specific request
    def destroy
      @request.destroy
      respond_to do |format|
        format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
        format.json { head :no_content }
      end
    end



private
  # Use callbacks to share common setup or constraints between actions.
  def set_request
    @request = Request.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def request_params
    params.require(:request).permit( :description, :completed, :user_id, :auto_id, service:[])
  end

end

app/helpers/requests_helper.rb
module RequestsHelper


end

app/views/requests/_appointment_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :selected_appointment %>
    <%= f.text_field :selected_appointment %>
  </div>
  <%= f.hidden_field :quote_id, value: quote.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
<% if @request.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@request.errors.count, "error") %>
    prohibited this request from being saved:</h2>

  <ul>
    <% @request.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<table>
  <tbody>
    <% @service_category.each do |cat| %>
    <tr>
      <td>
        <strong><%= cat.name %></strong></br>
        <div>
          <% cat.services.each do |rt| %>
          <%= f.label rt.name %>
          <%= f.check_box :service, { multiple: true }, rt.name, false %>
          <% end %>
        </div>
        <% end %>
        <div class="field">
          <%= f.label 'Describe problem:' %><br>
          <%= f.text_area :description %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/requests/_new_service.html.erb
<div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
   <h3 id="myModalLabel">Modal header</h3>
 </div>
 <div class="modal-body">
   **here comes whatever you want to show!**
 </div>
 <div class="modal-footer">
   <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
   <button class="btn btn-primary">Save changes</button>
 </div>

app/views/requests/_quote_form.html.erb
<%= form_for([@request, @request.quotes.build]) do |f|%>

<%= f.hidden_field :service_center_id, value: @service_center.id %>

<div class="col-md-6 col-sm-6">
  <div class="field">
    <%= f.label 'Quote' %>
    <br>
    <%= f.number_field :cost %>

  </div>
  <div class="field">
    <%= f.label 'Notes for customer' %><br>
    <%= f.text_area :comment %>
  </div>
</div>

<div class="col-md-6 col-sm-6">
  <p>
    Appointment times
  </p>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :datetime, 'First available' %>
        <div class="input-group date" id="datetimepicker1">
          <%= f.text_field :appointment1, class: 'form-control', data: { date_format: 'YYYY/MM/DD hh:mm' }%>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :datetime, 'Second available' %>
        <div class="input-group date" id="datetimepicker2">
          <%= f.text_field :appointment2, class: 'form-control', data: { date_format: 'YYYY/MM/DD hh:mm' } %>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :datetime, 'Third available' %>
        <div class="input-group date" id="datetimepicker3">
          <%= f.text_field :appointment3, class: 'form-control', data: { date_format: 'YYYY/MM/DD hh:mm' } %>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit 'Add Quote', class: 'btn btn-default'%>
  </div>
</div>
<% end %>

app/views/requests/add_quote.html.erb
<div class="container-overflow-wrap">
  <div class='container'>
    <div class='row'>
      <div class='m12'>
        <div class="container" style="margin-top:110px;height:100% !important;">
          <div class="row">
            <div class="col-md-12 col-sm-12">
              <h2><%= @service_center.service_center_name.capitalize %>
              </h2>
              Add a Quote for:
              <div>
                <p>Service:
                  <%= @request.service.to_sentence %></p>
                <p>Description:
                  <%= @request.description %></p>
                <p>Auto:
                  <%= @request.auto.year %>
                  <%= @request.auto.make %>
                  <%= @request.auto.model %>
                </p>
              </div>

              <div class="row">
                <div class="col-md-12 col-sm-12">

                  <%= render 'quote_form' %>

                </div>
              </div>
              <% if service_center_signed_in?%>
              <%= link_to 'Back', sc_dashboard_requests_path %>
            <% else %>
              <%= link_to 'back', requests_path %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
	<div class="container-overflow-wrap">
		  <div class="row banner02">
        <div class="container" style='padding: 0px 35px 35px 35px;'>
						<!--/////////////////// START WELCOME MESSAGE ROW /////////////////////-->
						<% if current_user.sign_in_count > 5 %>
						<div class="row welcome">
							<div class="col-md-12 col-sm-12">
								<h1>Welcome back
									<%= current_user.first_name.capitalize %></h1>
								We value you as a customer and strive to deliver a solution that is right for you.<br><br>
							</div>
						</div>
						<% end %>
						<% if current_user.sign_in_count < 2 %>
						<div class="row welcome">
							<div class="col-md-12 col-sm-12">
								<h1>Welcome,
									<%= current_user.first_name.capitalize %></h1>
								<h4>Thank you for letting us find the best deal in automotive repair. We strive to deliver a solution that is right for you.</h4><br><br>
							</div>
						</div>
						<% end %>
						<!--/////////////////// START NOTIFICATION ROW /////////////////////-->
						<% if @appointments.empty? or @appointments_uncomplete.empty? %>
						<div class="row apptRow"></div>
					<% else %>
						<div class="row apptRow">
							<div class="col-md-2 col-sm-12 apptHead" style="line-height:80px;height:80px;text-align:center;">
								<h3 style='margin-top:10px;margin-bottom:10px;'>You have a new<br>appointment!</h3>
							</div>
							<% @appointments_uncomplete.each do |a| %>
							<div class="col-md-4 col-sm-12" style="padding:0;">
								<div class="apptHead">Where & When</div>
								<div class="apptText"><%= a.quote.service_center.service_center_name %><br><%= a.selected_appointment %></div>
							</div>
							<div class="col-md-3 col-sm-12" style="padding:0;">
								<div class="apptHead">Your Vehicle</div>
								<div class="apptText"><%= a.quote.request.auto.year %><br><%= a.quote.request.auto.make %>
									<%= a.quote.request.auto.model %></div>
							</div>
							<div class="col-md-3 col-sm-12" style="padding:0;">
								<div class="apptHead">Services</div>
								<div class="apptText"><%= a.request.service.to_sentence if a.request.service %></div>
							</div>
							<% end %>
						</div>
						<% end %>

						<!--/////////////////// START MAINTENANCE LISTINGS COLUMN /////////////////////-->
						<div class="row">
							<div class="col-md-12 col-sm-12">
								<h3 class='light'>Your Maintenance Requests</h3>
								<ul class="nav nav-tabs">
									<li class="active">
										<a data-toggle="tab" href="#mainQuotes">Quotes</a>
									</li>
									<li class="inactive">
										<a data-toggle="tab" href="#mainAppointments">Appointments</a>
									</li>
									<li class="inactive">
										<a data-toggle="tab" href="#mainHistory">Past</a>
									</li>
								</ul>
								<div class="tab-content" style="border:solid 2px #ff6600;min-height: 350px;
						    overflow: scroll;">
									<!--/////////////////// QUOTES TAB /////////////////////-->
									<div id="mainQuotes" class="tab-pane fade in active">
										<% if @request.appointments.blank? %>
										<% r = @request %>
										<div class="row">
											<div class="col-md-12 col-sm-12">
												<h4><%= r.created_at.strftime("%m/%d/%y") %>
													-
													<%= r.auto.make %>
													<%= r.auto.model %>
													-
													<%= r.service.to_sentence %></h4>
												<% unless r.description.blank? %>
												Your comments:
												<i><%= r.description %></i><br>
												<% end %>
											</div>
										</div>
										<!--/////////////////// APPOINTMENT FORM /////////////////////-->

										<% if r.quotes.empty? %>
										<div class="row">
											<div class="col-md-6 col-sm-12">
												No Quotes yet, but our dogs are finding the best services
											</div>
										</div>
									<% else %>
										<% r.quotes.each do |q| %>
										<div class="row" style="margin-top:15px;">
											<div class="col-md-1 col-sm-1">
												<center>
													<i class="fa fa-chevron-circle-right fa-2x" aria-hidden="true" style="color:#ff6600;"></i>
												</center>
											</div>
											<div class="col-md-11 col-sm-11">
												<div class="row">
													<div class="col-md-4 col-sm-4">
														Service Center:
														<b><%= q.service_center.service_center_name %></b>
													</div>
													<div class="col-md-6 col-sm-6">
														Location:
														<b><%= q.service_center.address %>
															<%= q.service_center.city %>,
															<%= q.service_center.zipcode %></b>
													</div>
												</div>
												<div class="row" style="margin-top:15px; margin-bottom:15px;">
													<div class="col-md-2 col-sm-2">
														Bid Amount:
														<b>$
															<%= number_with_precision(q.cost, precision: 2) %></b>
													</div>
													<div class="col-md-5 col-sm-5">
														<%= form_for(@appointment) do |f| %>
														<%= f.hidden_field :quote_id, value: q.id %>
														<%= f.hidden_field :user_id, value: current_user.id %>
														<%= f.hidden_field :service_center_id, value: q.service_center_id %>
														<%= f.hidden_field :request_id, value: q.request_id %>
														<% if @appointment.errors.any? %>
														<div id="error_explanation">
															<h2><%= pluralize(@appointment.errors.count, "error") %>
																prohibited this appointment from being saved:</h2>
															<ul>
																<% @appointment.errors.full_messages.each do |message| %>
																<li><%= message %></li>
																<% end %>
															</ul>
														</div>
														<% end %>
														<b>Appointment:</b>
														<% if q.appointment1 %>
														<%= f.select :selected_appointment, [q.appointment1.strftime('%A, %d %b %Y %l:%M %P'), q.appointment2.strftime('%A, %d %b %Y %l:%M %P'), q.appointment3.strftime('%A, %d %b %Y %l:%M %P')], {}, {} %>
														<% end %>
													</div>
													<div class="actions">
														<div class="col-md-3 col-sm-3">
															<%= f.submit 'Save', class: "btn bth-default", id: "apptSelect", data: { confirm: "By selecting this appointment you agreed to arrive on time at the selected service shop" } %>
														</div>
													</div>
													<% end %>
												</div>
											</div>
										</div>
										<% end %>
										<% end %>
										<% elsif @request.appointments.first.completed? %>
										<div class="row">
											<div class="col-md-6 col-sm-12">
												<h4>Looks like it's time for a new
													<%= link_to "request.", new_request_path %></h4>
											</div>
										</div>
									<% else %>
										<div class="row">
											<div class="col-md-6 col-sm-12">
												<h4>Checkout the appointments tab!</h4>
											</div>
										</div>
										<% end %>
									</div>
									<!--/////////////////// APPOINTMENT TAB /////////////////////-->
									<div id="mainAppointments" class="tab-pane fade">
										<% if @appointments_uncomplete.empty? %>
										<div class="row">
											<div class="col-md-12 col-sm-12">
												<p>No Appointments yet.</p>
											</div>
										</div>
									<% else %>
										<% @appointments_uncomplete.each do |a| %>
										<div class="row">
											<div class="col-md-12 col-sm-12">
												<b><%= a.selected_appointment %></b>
												-
												<%= a.request.auto.make %>
												<%= a.request.auto.model %>
												-
												<%= a.request.service.to_sentence %><br>
												<% if a.request.description.blank? %>
											<% else %>
												Your comments:
												<i><%= a.request.description %></i><br>
												<% end %>
											</div>
										</div>
										<div class="row" style="margin-top:5px;">
											<div class="col-md-6 col-sm-12">
												Service Center:
												<b><%= a.quote.service_center.service_center_name.titleize %>,
													<%= a.quote.service_center.address %>,
													<%= a.quote.service_center.city %>
													<%= a.quote.service_center.zipcode %></b>
											</br>
											<% if a.quote.comment.blank? %>
										<% else %>
											Comments:
											<i><%= a.quote.comment %></i>
											<% end %>
										</div>
										<div class="col-md-3 col-sm-12">
											Bid Amount:
											<b><%= a.quote.cost %></b>
										</div>
									</div>
									<%end%>
									<%end%>
								</div>
								<!--/////////////////// HISTORY TAB /////////////////////-->
								<div id="mainHistory" class="tab-pane fade">
									<% @appointments.completed_true.each do |a| %>
									<div class="row" style="margin-top:15px;">
										<div class="col-md-12 col-sm-12">
											Completed:
											<b><%= a.updated_at.strftime("%m/%d/%y") %></b><br>
											Services:<b>
												<%= a.request.service.to_sentence %></b><br>
											Auto:
											<b><%= a.request.auto.year %>
												<%= a.request.auto.make %>
												<%= a.request.auto.model %></b>
										</div>
									</div>
									<div class="row">
										<div class="col-md-6 col-sm-12">
											Service Center:
											<b><%= a.quote.service_center.service_center_name %></b>
										</div>
										<div class="col-md-6 col-sm-12">
											Cost:
											<b><%= a.quote.cost %></b>
										</div>
									</div>
									<%end%>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

app/views/requests/new_service.js.erb
// $("#modal-window").find(".modal-content").html("<%= j (render 'new_service') %>");

app/views/requests/sc_dashboard.html.erb
<div class="container-overflow-wrap">
  <div class='row banner02'>
    <div class="container" style='padding: 0px 35px 45px 35px;'>
      <!-- Main page content -->
      <div class="row light">
        <div class="col-md-12 col-sm-12">
          <h3>
            <%= @service_center.service_center_name %>'s Personal Dashboard
          </h3>
          <p>Thank you for being a member since
            <%= @service_center.created_at.strftime('%Y')%></p><br/>

        </div>
      </div>
      <div class="row">
        <div class="col-md-12 col-sm-12">
          <ul class="nav nav-tabs">
            <li class="active">
              <a data-toggle="tab" href="#mainNew">New Requests
                <span class="badge"><%= @requests.count %>
                  <span></a>
                </li>
                <li class="inactive">
                  <a data-toggle="tab" href="#mainPending">Pending bids
                    <span class="badge"><%= @service_center_quotes.count %></span>
                  </a>
                </li>
                <li class="inactive">
                  <a data-toggle="tab" href="#mainAppointments">Appointments
                    <span class="badge"><%= @service_center.appointments.completed_false.count %></span>
                  </a>
                </li>
                <li class="inactive">
                  <a data-toggle="tab" href="#mainCompleted">Completed</a>
                </li>
              </ul>
              <div class="tab-content" style="border:solid 2px #ff6600;min-height: 350px;
    overflow: scroll;">
                <div id="mainNew" class="tab-pane fade in active">
                  <div class="row">
                    <div class="col-md-12 col-sm-12">
                      <table class='table table-hover'>
                        <thead>
                          <tr>
                            <th>Date</th>
                            <th>Vehicle</th>
                            <th>Request</th>
                            <th>description</th>
                            <th colspan="3"></th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @requests.each do |req| %>
                          <tr>
                            <td><%= req.created_at.strftime("%m-%d-%y") %></td>
                            <td><%= req.auto.year %>
                              <%= req.auto.make.capitalize %>
                              <%= req.auto.model.capitalize %></td>
                            <td><%= req.service.to_sentence %></td>
                            <td><%= req.description %></td>
                            <td><%= link_to 'Add quote', add_quote_url(req), class: "btn btn-default" %></td>
                            <% end %>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
                <div id="mainPending" class="tab-pane fade">
                  <div class="row">
                    <div class="col-md-12 col-sm-12">
                      <table class='table table-hover'>
                        <thead class="thead-default">
                          <tr>
                            <th>Date</th>
                            <th>Vehicle</th>
                            <th>Request</th>
                            <th>Description</th>
                            <th>Quote</th>
                            <th colspan="3"></th>
                          </tr>
                        </thead>
                        <tbody>
                          <%  @service_center_quotes.each do |q| %>
                          <tr>
                            <!-- changing col date formatting.(just a note) -->
                            <td>
                              <nobr><%= q.request.created_at.strftime("%m/%d/%y") %></nobr>
                            </td>
                            <td><%= q.request.auto.year %>
                              <%= q.request.auto.make.capitalize %>
                              <%= q.request.auto.model.capitalize %></td>
                            <td><%= q.request.service.to_sentence %></td>
                            <td><%= q.request.description %></td>
                            <td><%= number_with_precision(q.cost, precision: 2) %></td>
                          </tr>
                          <% end %>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
                <div id="mainAppointments" class="tab-pane fade">

                  <div class="row">
                    <div class="col-md-12 col-sm-12">
                      <table class='table table-hover'>
                        <thead class="thead-default">
                          <tr>
                            <th>Appointment Date</th>
                            <th>Customer</th>
                            <th>Vehicle</th>
                            <th>Request</th>
                            <th>Description</th>
                            <th>Quote</th>
                          </tr>
                        </thead>
                        <% if @service_center.appointments.empty? %>
                        <div class="row">
                          <div class="col-md-12 col-sm-12">
                            No appointments yet
                          </div>
                        </div>
                      <% else %>
                        <tbody>
                          <%  @service_center.appointments.completed_false.each do |a| %>
                          <tr>
                            <td><%= a.selected_appointment %></td>
                            <td><%= a.user.first_name %></td>
                            <td><%= a.request.auto.year %>
                              <%= a.request.auto.make.capitalize %>
                              <%= a.request.auto.model.capitalize %></td>
                            <td><%= a.request.service.to_sentence %></td>
                            <td><%= a.request.description %></td>
                            <td><%= a.quote.cost %></td>
                            <td><%= link_to 'Complete', complete_request_path(a), method: :put, class: "btn btn-default", data: { confirm: 'Are you sure this appointment is completed?'} %></td>
                          </tr>
                          <% end %>
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <% end %>
                </div>

                <div id="mainCompleted" class="tab-pane fade">
                  <div class="row">
                    <div class="col-md-12 col-sm-12">
                      <table class='table table-hover'>
                        <thead class="thead-default">
                          <tr>
                            <th>Completed Date</th>
                            <th>Vehicle</th>
                            <th>Request</th>
                            <th>cost</th>
                          </tr>
                        </thead>
                        <tbody>
                          <%  @service_center.appointments.completed_true.each do |c| %>

                          <tr>
                            <td><%= c.updated_at.strftime("%m-%d-%y") %></td>
                            <td><%= c.request.auto.year %>
                              <%= c.request.auto.make.capitalize %>
                              <%= c.request.auto.model.capitalize %></td>
                            <td><%= c.request.service.to_sentence %></td>
                            <td><%= c.quote.cost %></td>
                          </tr>
                          <% end %>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/requests/show.html.erb
<div class="container-overflow-wrap">
  <div class='container'>
    <div class='row'>
      <div class='m12'>
        <div class="container" style="margin-top:110px;height:100% !important;">
          <div class="row">
            <div class="col-md-12 col-sm-12">
              <h4>8/22/16 - Oil Change Synthetic Blend | Brake Inspection</h4>
              Your comments:
              <i>"I think my rotors are worn because my car pulls the the left when I apply the brakes"</i>
            </div>
          </div>
          <div class="row" style="margin-top:15px;">
            <div class="col-md-1 col-sm-1">
              <center>
                <i class="fa fa-chevron-circle-right fa-2x" aria-hidden="true" style="color:#ff6600;"></i>
              </center>
            </div>
            <div class="col-md-11 col-sm-11">
              <div class="row">
                <div class="col-md-4 col-sm-4">
                  Service Center:
                  <b>Newcastle service center</b>
                </div>
                <div class="col-md-4 col-sm-4">
                  Location:
                  <b>16352 west end Newcastle 98056</b>
                </div>
              </div>
              <div class="row" style="margin-top:15px;">
                <div class="col-md-2 col-sm-2">
                  Bid Amount:
                  <b>$85.00</b>
                </div>
                <div class="col-md-6 col-sm-6">
                  Appointment times:
                  <select>
                    <option value="">Friday, Oct 4 at 11:00am</option>
                    <option value="">Saturday, Oct 5 at 10:30am</option>
                    <option value="">Saturday, Oct 5 at 12:00pm</option>
                  </select>

                </div>
                <div class="col-md-3 col-sm-3">
                  <button class="btn btn-default btn-sm">ACCEPT</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>