config/routes.rb
Rails.application.routes.draw do



  get 'user/index'

  get 'user/dashboard'

  get 'service_center/index'

  get 'service_center/dashboard'

# devise routes
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_for :service_centers, path: 'service_centers', controllers: { sessions: "service_centers/sessions", registrations: "service_centers/registrations" }

#routes
  resources :appointments, only: [:create, :update, :destroy]
  resources :autos, only: [:new, :create]

  match '/requests/appointments/complete/:id' => 'requests#complete', as: 'complete_request', via: :put

# nested routes
  resources :requests do
    resources :quotes
    collection do
      get "sc_dashboard" # generate  get "/requests/sc_dashboard"
    end
  end
  # resources :services, only: [:index]

# custom routes
  get "new_service", to: 'requests#new_service', as: :new_service
  
  get '/requests/add_quote/:id', to: 'requests#add_quote', as: 'add_quote'

  get "welcome", to: "welcome#index", as: :welcome


# root
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :quote
  belongs_to :request
  belongs_to :user
  belongs_to :service_center
  validates :selected_appointment, presence: true

def self.completed_true
  where(completed: "true")
end
def self.completed_false
  where(completed: "false")
end

end

app/models/auto.rb
class Auto < ApplicationRecord

  validates :make, presence: true
  validates :model, presence: true
  validates :year, presence: true
  validates :trim, presence: true
  validates :mileage, presence: true


  belongs_to :user
  has_many :requests, dependent: :destroy
  has_many :quotes, through: :requests
  has_many :appointments, through: :quotes

end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :request
  belongs_to :service_center

  has_one :appointment, dependent: :destroy

  validates :cost, presence: true
  validates :cost, numericality: true
  validates :appointment1,  presence: true
  validates :appointment2,  presence: true
  validates :appointment3,  presence: true

def self.no_appointments
  left_outer_joins(:appointment).where(appointments: {id: nil})
end

end

app/models/request.rb
class Request < ApplicationRecord
  before_validation :format_service
  belongs_to :user
  belongs_to :auto
  has_many :quotes, dependent: :destroy
  has_many :appointments, through: :quotes

  validates :service, presence: true

  serialize :service

  validates_associated :quotes

  def self.no_appointments
    left_outer_joins(:appointments).where(appointments: {id: nil})
  end
  def self.no_completed_appointments
    left_outer_joins(:appointments).where(appointments: {completed: false})
  end
  def self.completed_appointments
    left_outer_joins(:appointments).where(appointments: {completed: true})
  end

  def format_service
    self.service = service.compact.reject(&:empty?)
  end

  def display_as_sentence
    self.compact.reject(&:empty?).to_sentence
  end

  def self.with_no_quotes_by(service_center)
  joins(:quotes).
    where.not(quotes: { service_center_id: service_center.id })
  end

end

app/models/request_service.rb
class RequestService < ApplicationRecord

end

app/models/service.rb
class Service < ApplicationRecord

end

app/models/service_center.rb
class ServiceCenter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

validates :first_name,          presence: true
validates :last_name,           presence: true
validates :service_center_name, presence: true
validates :zipcode,             presence: true
validates :address,             presence: true
validates :city,                presence: true
validates :state,               presence: true
validates :zipcode,             presence: true
validates :phone_number,        presence: true
validates :email,               presence: true


has_many :quotes
has_many :appointments

end

class ServiceCenter::ParameterSanitizer < Devise::ParameterSanitizer
  def initialize(*)
    super
    permit(:sign_up, keys: [:first_name, :last_name, :service_center_name, :address, :zipcode, :city, :state, :phone_number, :email])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name,  presence: true
  validates :last_name,   presence: true
  validates :zipcode,     presence: true


  has_many :autos
  has_many :requests
  has_many :quotes, through: :requests
  has_many :appointments, through: :quotes

  accepts_nested_attributes_for :autos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :requests, allow_destroy: true
end






class User::ParameterSanitizer < Devise::ParameterSanitizer
  def initialize(*)
    super
    permit(:sign_up, keys: [:first_name, :last_name, :zipcode, :email])
  end
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_auto, only: [ :show, :edit, :update, :destroy ]

  include Edmunds_get

  # GET /autos
  # GET /autos.json
  def index
    @autos = Auto.all
  end

  # GET /autos/1
  # GET /autos/1.json
  def show
  end

  # GET /autos/new
  def new
    @auto = Auto.new
    @auto.user = current_user
    @get_years = get_years
  end

  # GET /autos/1/edit
  def edit
  end

  # POST /autos
  # POST /autos.json
  def create
    @auto = Auto.new(auto_params)

    respond_to do |format|
      if @auto.save
        format.html { redirect_to new_request_path, notice: 'Auto was successfully created.' }
        format.json { render :show, status: :created, location: @auto }
      else
        format.html { render :new }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autos/1
  # PATCH/PUT /autos/1.json
  def update
    respond_to do |format|
      if @auto.update(auto_params)
        format.html { redirect_to @auto, notice: 'Auto was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto }
      else
        format.html { render :edit }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autos/1
  # DELETE /autos/1.json
  def destroy
    @auto.destroy
    respond_to do |format|
      format.html { redirect_to autos_url, notice: 'Auto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto
      @auto = Auto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_params
      params.require(:auto).permit(:make, :model, :year, :trim, :mileage, :image, :user_id)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  before_action :authenticate_service_center!
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def create
      @request = Request.find(params[:request_id])
      @quote = @request.quotes.create(quote_params)
      if @quote.save
        redirect_to :sc_dashboard_requests
      else
        flash[:notice] = "Error creating comment: #{@quote.errors.inspect}"
        redirect_back(fallback_location: request)
      end
  end



  private

    def set_quote
      @quote = Quote.find(params[:id])
    end


    def quote_params
      params.require(:quote).permit(:cost, :comment, :request_id, :appointment1, :appointment2, :appointment3, :service_center_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/autos_helper.rb
module AutosHelper

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper


end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_defaultnavbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar.html.erb
<div class='container'>
  <div class='row'>
    <% if service_center_signed_in? %>
    <div class="navbar-text pull-left">

    </div>
    <% else %>
    <div class="navbar-text pull-left">
      <p><%= link_to 'New Auto', new_auto_path, class: "btn btn-default" %>
      <%= link_to 'Requests', requests_path, class: "btn btn-default" %>
      <%= link_to 'New Request', new_request_path, class: "btn btn-default" %>

      <%= link_to 'Sign in as service center', new_service_center_session_path, class: "btn btn-default" %>
      <%= link_to 'Sign up service center', new_service_center_registration_path, class: 'btn btn-default' %></p>
      

    </div>
    <% end %>

    <div class="navbar-text pull-right">
    <% if user_signed_in? %>
      <p>Welcome, <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></p>
    <% elsif service_center_signed_in? %>
        <p>Welcome, <strong><%= current_service_center.first_name %></strong> |
        <%= link_to 'Edit profile', edit_service_center_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Sign out", destroy_service_center_session_path, method: :delete, :class => 'navbar-link'  %></p>
    <% else %>
      <%= form_for(:user, :url => session_path(:user), html: { class: "navbar-form navbar-right form-inline" }) do |f| %>
        <div class="form-group">
          <%= f.text_field :email, :placeholder => "Email", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, :placeholder => "Password", class: "form-control"  %>
        </div>
        <div class="checkbox">
          <%= f.check_box :remember_me %><%= f.label :remember_me %>
        </div>
        <%= f.submit 'Login', class: "btn btn-default", style: 'margin-right: 5px;' %> Or <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link btn btn-default', style: 'margin-left: 5px;' %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar2.html.erb
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Welcome, <strong><%= current_user.email %></strong> |
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |

  <%= form_for(:user, :url => session_path(:user), html: { class: "navbar-form navbar-right form-inline" }) do |f| %>
    <div class="form-group">
      <%= f.text_field :email, :placeholder => "Email", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.password_field :password, :placeholder => "Password", class: "form-control"  %>
    </div>
    <div class="checkbox">
      <%= f.check_box :remember_me %><%= f.label :remember_me %>
    </div>
    <%= f.submit 'Login', class: "btn btn-default" %>
    <% end %>
<% end %>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>WrenchRoverApp</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/meganavbar' %>
    <main>
      <% if notice %>
        <p class="alert alert-success alert-dismissible" role="alert"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger alert-dismissible" role="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </main>
      <footer class="footer" style="display:none;">
        <div class="container">
          <div class="row">
            <div class="WRfooterLinks">
                <a href="#">Contact Us</a> | <a href="#">Partners</a> | <a href="#">FAQ</a>
                <% if service_center_signed_in? %> |
                <%= link_to "Service Center Sign out", destroy_service_center_session_path, method: :delete, :class => 'navbar-link'  %>
                <% elsif user_signed_in? %> |
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                <% end %>
            </div>
          </div>
          <div class="row">
            <div>
              Designed and built with all the love in the world by the WrenchRover Team. Maintained by the core dev team with the help of our contributors.
            </div>
          </div>
          <div class="row">
            <div>Version: v1-alpha | Copyright &copy; WrenchRover 2017
            </div>
        </div>
      </div>
    </footer>
  </body>
</html>